importpathsaddchilddirs("/usr/farmtech_v001/")

importsafe "navigation"
importsafe "tool"
importsafe "actionsequence"
importsafe "farm"
importsafe "json"

importpathsremove("/usr/farmtech_v001/botactions")

importsafe "bot_0_subroutine"
importsafe "bot_1_subroutine"
importsafe "bot_2_subroutine"
importsafe "bot_3_subroutine"
importsafe "bot_4_subroutine"
importsafe "bot_5_subroutine"
importsafe "bot_6_subroutine"
importsafe "bot_7_subroutine"
importsafe "bot_8_subroutine"
